name: Lint proto files

on:
  push:

permissions:
  contents: read

jobs:
  buf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> 0c35cf20c (Increase buf version to v1.11.0 (#2388))
      - uses: bufbuild/buf-setup-action@v1.11.0
        with:
          github_token: ${{ github.token }}
=======
      - uses: bufbuild/buf-setup-action@v1.9.0
>>>>>>> 51f21a85b (Update buf to v1.9.0 (#2239))
=======
      - uses: bufbuild/buf-setup-action@v1.9.0 # TODO: use "v1.10.0"
<<<<<<< HEAD
>>>>>>> 1c0e00460 (Bump buf dependency to v1.10.0 (#2339))
=======
        with:
          github_token: ${{ github.token }}
>>>>>>> 6bf817bb8 (Add proposer list to proposer.Windower (#2366))
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: "proto"
